import { Suspense, lazy } from 'react;;;
import { Route, Routes } from 'react-router-dom;;;
import Navigation from './components/Navigation;
;;;
const Home = lazy(() => import('./pages/Home'));
const About = lazy(() => import('./pages/About'));
const Contact = lazy(() => import('./pages/Contact'));
;
function App() {;
  return (;
    <div className="App">;
      <Navigation />;
      <Suspense fallback={<div>Loading...</div>}>;
        <Routes>;
          <Route path="/" element={<Home />} />;
          <Route path="/about" element={<About />} />;
          <Route path="/contact" element={<Contact />} />;
        </Routes>;
      </Suspense>;
    </div>;
  );
};
export default App;