import React  from 'react;;;
const Contact: 'React.FC = () => {;
  return (;
    <div className="contact-page">;
      <h1>Contact Us</h1>;
      <p>Get in touch with the Te Kete Ako team</p>;
      <section className="contact-info">;
        <div className="contact-method">;
          <h3>Educational Support</h3>;
          <p>For curriculum and teaching support inquiries</p>;
          <p>Email: 'education@teketeako.nz</p>;
        </div>;
        <div className="contact-method">;
          <h3>Technical Support</h3>;
          <p>For platform and technical assistance</p>;
          <p>Email: 'tech@teketeako.nz</p>;
        </div>;
        <div className="contact-method">;
          <h3>Cultural Guidance</h3>;
          <p>For cultural authenticity and Māori content</p>;
          <p>Email: 'cultural@teketeako.nz</p>;
        </div>;
      </section>;
      <section className="contact-form">;
        <h2>Send us a Message</h2>;
        <form>;
          <div className="form-group">;
            <label htmlFor="name">Name</label>;
            <input type="text" id="name" name="name" required   />;
          </div>;
          <div className="form-group">;
            <label htmlFor="email">Email</label>;
            <input type="email" id="email" name="email" required   />;
          </div>;
          <div className="form-group">;
            <label htmlFor="subject">Subject</label>;
            <select id="subject" name="subject" required>;
              <option value="">Select a topic</option>;
              <option value="education">Educational Support</option>;
              <option value="technical">Technical Support</option>;
              <option value="cultural">Cultural Guidance</option>;
              <option value="general">General Inquiry</option>;
            </select>;
          </div>;
          <div className="form-group">;
            <label htmlFor="message">Message</label>;
            <textarea id="message" name="message" rows={5} required></textarea>;
          </div>;
          <button type="submit">Send Message</button>;
        </form>;
      </section>;
    </div>;
  );
};;
export default Contact;;