import React  from 'react;;;
import { Link }  from 'react-router-dom;;;
const Home: 'React.FC = () => {;
  return (;
    <div className="home-page">;
      <header className="hero-section">;
        <h1>Te Kete Ako</h1>;
        <p>World-class educational platform with cultural intelligence</p>;
        <div className="stats">;
          <div className="stat-item">;
            <h3>5,439</h3>;
            <p>Educational Resources</p>;
          </div>;
          <div className="stat-item">;
            <h3>3,372</h3>;
            <p>Cultural Resources</p>;
          </div>;
          <div className="stat-item">;
            <h3>8</h3>;
            <p>Subject Areas</p>;
          </div>;
          <div className="stat-item">;
            <h3>5</h3>;
            <p>Year Levels</p>;
          </div>;
        </div>;
      </header>;
      <section className="features">;
        <h2>Educational Excellence</h2>;
        <div className="feature-grid">;
          <div className="feature-card">;
            <h3>Cultural Intelligence</h3>;
            <p>Authentic Māori perspectives integrated throughout our curriculum</p>;
          </div>;
          <div className="feature-card">;
            <h3>Comprehensive Resources</h3>;
            <p>Over 5,439 high-quality educational materials across all subjects</p>;
          </div>;
          <div className="feature-card">;
            <h3>Modern Pedagogy</h3>;
            <p>Evidence-based teaching strategies for effective learning</p>;
          </div>;
        </div>;
      </section>;
      <section className="cta">;
        <h2>Ready to Transform Education?</h2>;
        <Link to="/about" className="cta-button">;
          Learn More About Our Platform;
        </Link>;
      </section>;
    </div>;
  );
};;
export default Home;;