import React, { useState }  from 'react;;;
const Year8SocialStudies: 'React.FC = () => {;
  const [activeUnit', setActiveUnit] = useState<string>(overview);
  const units = [;
    {;
      id: 'overview',;
      title: 'Year 8 Social Studies Overview',;
      description: 'Exploring New Zealand society, history, and global connections',;
      content: '(;
        <div className="unit-content">;
          <h3>Welcome to Year 8 Social Studies</h3>;
          <p>;
            In Year 8, we explore how societies work and change, with a focus on;
            New Zealand's unique position in the world.;
          </p>;
        </div>;
      );
    },;
    {;
      id: 'identity',;
      title: 'Identity, Culture, and Organization',;
      description: 'Understanding how people organize themselves and express their identity',;
      content: '(;
        <div className="unit-content">;
          <h3>Identity, Culture, and Organization</h3>;
          <p>;
            Explore how individuals and groups express their identity and organize;
            themselves in society.;
          </p>;
          <div className="activities">;
            <button className="activity-btn" onClick={() => alert(Cultural Identity Discussion)}>;
              Cultural Identity Discussion;
            </button>;
            <button className="activity-btn" onClick={() => alert(Community Mapping Activity)}>;
              Community Mapping;
            </button>;
          </div>;
        </div>;
      );
    },;
    {;
      id: 'place',;
      title: 'Place and Environment',;
      description: 'Understanding how people interact with places and environments',;
      content: '(;
        <div className="unit-content">;
          <h3>Place and Environment</h3>;
          <p>;
            Investigate how people interact with places and environments, and how;
            this affects society.;
          </p>;
          <div className="activities">;
            <button className="activity-btn" onClick={() => alert(Environmental Impact Study)}>;
              Environmental Impact Study;
            </button>;
            <button className="activity-btn" onClick={() => alert(Place Investigation Activity)}>;
              Place Investigation;
            </button>;
          </div>;
        </div>;
      );
    },;
    {;
      id: 'continuity',;
      title: 'Continuity and Change',;
      description: 'Understanding how societies change over time',;
      content: '(;
        <div className="unit-content">;
          <h3>Continuity and Change</h3>;
          <p>;
            Explore how societies change over time and what remains constant.;
          </p>;
          <div className="activities">;
            <button className="activity-btn" onClick={() => alert(Timeline Creation Activity)}>;
              Timeline Creation;
            </button>;
            <button className="activity-btn" onClick={() => alert(Change Analysis Activity)}>;
              Change Analysis;
            </button>;
          </div>;
        </div>;
      );
    },;
    {;
      id: 'economic',;
      title: 'The Economic World',;
      description: 'Understanding how economic decisions affect people and communities',;
      content: '(;
        <div className="unit-content">;
          <h3>The Economic World</h3>;
          <p>;
            Investigate how economic decisions affect people, communities, and nations.;
          </p>;
          <div className="activities">;
            <button className="activity-btn" onClick={() => alert(Economic Decision Making Activity)}>;
              Economic Decision Making;
            </button>;
            <button className="activity-btn" onClick={() => alert(Budget Planning Activity)}>;
              Budget Planning;
            </button>;
          </div>;
        </div>;
      );
    };
  ];
  return (;
    <div className="year8-social-studies">;
      <div className="page-header">;
        <h1>Year 8 Social Studies</h1>;
        <p className="subtitle">Exploring New Zealand Society, History, and Global Connections</p>;
      </div>;
      <nav className="unit-nav">;
        {units.map(unit => (;
          <button;
            key={unit.id};
            className={`unit-btn ${activeUnit === unit.id ? active : }`};
            onClick={() => setActiveUnit(unit.id)};
          >;
            {unit.title};
          </button>;
        ))};
      </nav>;
      <main className="content-area">;
        {units.find(unit => unit.id === activeUnit)?.content};
      </main>;
    </div>`;
  );``;
};```;
export default Year8SocialStudies;````;