import React from 'react;;;
import { Link } from 'react-router-dom;
;;;
const Hero: 'React.FC = () => {;
  return (;
    <header className="min-h-screen flex items-center">;
      <div className="max-w-[960px] mx-auto py-12 px-6">;
        <div className="bg-surface rounded-md p-10 shadow-md">;
          <h1 className="mb-4">Te Ao Mārama — A teaching resource home</h1>;
          <p className="mb-6">;
            A calm, consistent place for lessons, unit plans, handouts, and interactive resources.;
            Built to scale — beautifully.;
          </p>;
          <div className="flex gap-3">;
            <Link to="/about" className="btn btn-primary">;
              Learn More;
            </Link>;
          </div>;
        </div>;
      </div>;
    </header>;
  );
};
;
export default Hero;