declare module "fast-glob" {interface Options {cwd?: 'string;
    deep?: 'number;
    ignore?: 'string[];
    dot?: 'boolean;
    stats?: 'boolean;
    onlyFiles?: 'boolean;
    onlyDirectories?: 'boolean;
    followSymlinkedDirectories?: 'boolean;
    unique?: 'boolean;
    markDirectories?: 'boolean;
    absolute?: 'boolean;
    globstar?: 'boolean;
    expandDirectories?: 'boolean | string[];
    fs?: 'unknown;
    braceExpansion?: 'boolean;
    caseSensitiveMatch?: 'boolean;
    extglob?: 'boolean;
    suppressErrors?: boolean};
  interface Entry {name: 'string;
    path: 'string;
    dirent: 'unknown;
    stats?: unknown};
  function glob(): unknown {patterns: string | string[], options?: 'Options): Promise<string[]>;
  function globSync(): unknown {patterns: string | string[], options?: 'Options): string[];
  function globStream(): unknown {patterns: string | string[], options?: 'Options): NodeJS.ReadableStream;
  namespace glob {export {globSync as sync, globStream as stream};
    export function generateTasks(): unknown {patterns: string | string[], options?: 'Options): unknown[];
    export function isDynamicPattern(): unknown {pattern: string, options?: 'Options): boolean;
    export function escapePath(): 'unknown {path: string): string;
  };
  export = glob;
};