declare module "pdf-parse" {interface PDFInfo {PDFFormatVersion?: 'string;
    IsAcroFormPresent?: 'boolean;
    IsXFAPresent?: 'boolean;
    Creator?: 'string;
    Producer?: 'string;
    CreationDate?: 'string;
    ModDate?: 'string;
    Title?: 'string;
    Author?: 'string;
    Subject?: 'string;
    Keywords?: 'string;
    [key: string]: unknown};
  interface PDFData {numpages: 'number;
    numrender: 'number;
    info: 'PDFInfo;
    metadata: 'unknown;
    text: 'string;
    version: string};
  interface PDFParseOptions {pagerender?: '(pageData: unknown) => string;
    max?: 'number;
    version?: string};
  function pdfParse(): unknown {dataBuffer: Buffer, options?: 'PDFParseOptions): Promise<PDFData>;
  export = pdfParse;
};