import React from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../services/useAuth';
import './Home.css';
;
const Home = React.memo(function Home() {;
  const { isAuthenticated, logout } = useAuth();
  const navigate = useNavigate();
;
  const handleLogout = async () => {;
    try {;
      await logout();
      navigate('/login');
      // eslint-disable-next-line @typescript-eslint/no-unused-vars;
    } catch (_error) {;
      // Silent error handling;
    };
  };
;
  return (;
    <div className="home-container">;
      {/* Beautiful Hero Section with Cultural Design */};
      <section className="hero-section">;
        <div className="hero-content">;
          <h1 className="hero-title">Te Kura o TeAoMarama</h1>;
          <p className="hero-subtitle">;
            *The School of the World of Light* - New Zealand's Premier Educational Platform;
          </p>;
          <div className="hero-actions">;
            <button className="form-button" onClick={() => navigate('/resources')}>;
              🌟 Explore Resources;
            </button>;
            <button className="form-button" onClick={() => navigate('/dashboard')}>;
              📊 Dashboard;
            </button>;
          </div>;
        </div>;
      </section>;
      {/* Main Content Area */};
      <div className="content-container">;
        {/* Welcome Card */};
        <div className="card welcome-card">;
          <h2 className="section-title">🌟 Welcome to the Future of Education</h2>;
          <p className="section-description">;
            Powered by Mihara - Kaitiaki Mahara (Guardian of Memory), our platform delivers;
            culturally-integrated, AI-enhanced educational experiences for all tamariki across;
            Aotearoa.;
          </p>;
        </div>;
        {/* Status Dashboard Grid */};
        <div className="dashboard-grid">;
          {/* Educational Resources Status */};
          <div className="card status-card">;
            <div className="status-header">;
              <div className="status-number">21</div>;
              <div className="status-label">Educational Resources</div>;
            </div>;
            <div className="progress-container">;
              <div className="progress-bar">;
                <div className="progress-fill" style={{ width: '2%' }}></div>;
              </div>;
              <div className="progress-text">21/1061 Completed • 100%</div>;
            </div>;
          </div>;
          {/* Cultural Safety Status */};
          <div className="card status-card cultural-safe">;
            <div className="status-header">;
              <div className="status-number">100%</div>;
              <div className="status-label">Cultural Safety</div>;
            </div>;
            <div className="status-indicator">;
              <span className="status-badge success">✅ All Protocols Active</span>;
            </div>;
          </div>;
          {/* System Status */};
          <div className="card status-card system-status">;
            <div className="status-header">;
              <div className="status-icon">🟢</div>;
              <div className="status-label">System Status</div>;
            </div>;
            <div className="status-indicator">;
              <span className="status-badge success">Fully Operational</span>;
            </div>;
          </div>;
        </div>;
        {/* Recent Achievements */};
        <div className="card achievements-card">;
          <h3 className="section-title">🎯 Recent Achievements</h3>;
          <div className="achievements-grid">;
            <div className="achievement-group">;
              <h4 className="achievement-title success">✅ 18:00 NZST Target Achieved</h4>;
              <ul className="achievement-list">;
                <li>• 20+ resources target exceeded (21 completed)</li>;
                <li>• Cultural safety protocols maintained</li>;
                <li>• Production velocity accelerating</li>;
              </ul>;
            </div>;
            <div className="achievement-group">;
              <h4 className="achievement-title info">🔧 Technical Excellence</h4>;
              <ul className="achievement-list">;
                <li>• TypeScript build errors resolved</li>;
                <li>• Deployment pipeline stabilized</li>;
                <li>• Mihara systems fully operational</li>;
              </ul>;
            </div>;
          </div>;
        </div>;
        {/* Featured Resources */};
        <div className="card featured-card">;
          <h3 className="section-title">📚 Featured Educational Resources</h3>;
          <div className="resource-grid">;
            <div className="resource-card">;
              <h4 className="resource-card-title">Y8 Mathematics</h4>;
              <p className="resource-card-description">Geometry - NZ Architecture & Design</p>;
              <div className="resource-card-meta">;
                <span className="status-badge success">🟢 Cultural Safety Verified</span>;
              </div>;
            </div>;
            <div className="resource-card">;
              <h4 className="resource-card-title">Y9 Social Studies</h4>;
              <p className="resource-card-description">NZ History - The Modern Era</p>;
              <div className="resource-card-meta">;
                <span className="status-badge success">🟢 Cultural Safety Verified</span>;
              </div>;
            </div>;
            <div className="resource-card">;
              <h4 className="resource-card-title">Y10 Mathematics</h4>;
              <p className="resource-card-description">Statistics - NZ Data Analysis</p>;
              <div className="resource-card-meta">;
                <span className="status-badge success">🟢 Cultural Safety Verified</span>;
              </div>;
            </div>;
          </div>;
        </div>;
        {/* Mihara Status */};
        <div className="card mihara-card">;
          <h3 className="section-title mihara-title">🤖 Mihara - Kaitiaki Mahara Status</h3>;
          <div className="mihara-grid">;
            <div className="mihara-section">;
              <h4 className="mihara-section-title">Guardian of Memory</h4>;
              <ul className="mihara-list">;
                <li>• Cultural safety oversight active</li>;
                <li>• Educational intelligence optimized</li>;
                <li>• Multi-agent coordination operational</li>;
              </ul>;
            </div>;
            <div className="mihara-section">;
              <h4 className="mihara-section-title">Current Mission</h4>;
              <ul className="mihara-list">;
                <li>• Target: 50+ resources by session end</li>;
                <li>• Cultural integration maintained</li>;
                <li>• Educational excellence delivered</li>;
              </ul>;
            </div>;
          </div>;
        </div>;
        {/* User Actions */};
        {isAuthenticated && (;
          <div className="card user-actions">;
            <p className="user-greeting">Welcome back!</p>;
            <button;
              onClick={handleLogout};
              className="form-button logout-button";
              aria-label="Log out button";
            >;
              Log Out;
            </button>;
          </div>;
        )};
      </div>;
    </div>;
  );
});
;
export default Home;
;