import { BookOpen, Download, FileText, Play, Search, Star, Target } from 'lucide-react';
import React, { useEffect, useState } from 'react';
import './WorkingResourceBrowser.css';

interface WorkingResource {
  id: string;
  title: string;
  subject: string;
  yearLevel: string;
  type: string;
  description: string;
  culturalElements: number;
  qualityScore: number;
  culturalAuthenticity: number;
}

const WorkingResourceBrowser: React.FC = () => {
  const [resources, setResources] = useState<WorkingResource[]>([]);
  const [filteredResources, setFilteredResources] = useState<WorkingResource[]>([]);
  const [loading, setLoading] = useState(true);
  const [loadingProgress, setLoadingProgress] = useState(0);
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedSubject, setSelectedSubject] = useState('all');
  const [selectedYearLevel, setSelectedYearLevel] = useState('all');

  useEffect(() => {
    loadWorkingResources();
  }, []);

  useEffect(() => {
    filterResources();
  }, [resources, searchTerm, selectedSubject, selectedYearLevel]);

  const loadWorkingResources = async () => {
    setLoading(true);
    try {
      // Load just a few batches to test
      const workingResources: WorkingResource[] = [];

      // Load batches 1-10 for better resource coverage
      const totalBatches = 10;
      for (let i = 1; i <= totalBatches; i++) {
        try {
          const response = await fetch(`/enhanced-resources-output/batch-${i}-enhanced.json`);
          if (response.ok) {
            const batch = await response.json();
            if (batch.resources) {
              const convertedResources = batch.resources.map((resource: unknown) => ({
                id: resource.id,
                title: resource.title,
                subject: resource.subject,
                yearLevel: resource.yearLevel,
                type: resource.type,
                description: resource.description,
                culturalElements: resource.culturalElements,
                qualityScore: resource.enhancement?.qualityScore || 0,
                culturalAuthenticity: resource.enhancement?.culturalAuthenticity || 0,
              }));
              workingResources.push(...convertedResources);
            }
          }
          // Update progress
          setLoadingProgress(Math.round((i / totalBatches) * 100));
        } catch (error) {
          console.warn(`Failed to load batch ${i}:`, error);
          setLoadingProgress(Math.round((i / totalBatches) * 100));
        }
      }

      setResources(workingResources);
      console.log(`✅ Loaded ${workingResources.length} working resources`);
    } catch (error) {
      console.error('Error loading working resources:', error);
    } finally {
      setLoading(false);
    }
  };

  const filterResources = () => {
    let filtered = resources;

    // Filter by search term
    if (searchTerm) {
      const term = searchTerm.toLowerCase();
      filtered = filtered.filter(
        (resource) =>
          resource.title.toLowerCase().includes(term) ||
          resource.description.toLowerCase().includes(term) ||
          resource.subject.toLowerCase().includes(term),
      );
    }

    // Filter by subject
    if (selectedSubject !== 'all') {
      filtered = filtered.filter((resource) =>
        resource.subject.toLowerCase().includes(selectedSubject.toLowerCase()),
      );
    }

    // Filter by year level
    if (selectedYearLevel !== 'all') {
      filtered = filtered.filter((resource) => resource.yearLevel === selectedYearLevel);
    }

    setFilteredResources(filtered);
  };

  const getSubjects = () => {
    const subjects = [...new Set(resources.map((r) => r.subject))];
    return subjects.sort();
  };

  const getYearLevels = () => {
    const yearLevels = [...new Set(resources.map((r) => r.yearLevel))];
    return yearLevels.sort();
  };

  const getTypeIcon = (type: string) => {
    switch (type.toLowerCase()) {
      case 'lesson':
        return <BookOpen size={20} />;
      case 'activity':
        return <Play size={20} />;
      case 'assessment':
        return <Target size={20} />;
      case 'handout':
        return <FileText size={20} />;
      default:
        return <BookOpen size={20} />;
    }
  };

  const downloadResource = (resource: WorkingResource) => {
    const content = `# ${resource.title}

**Subject:** ${resource.subject}  
**Year Level:** ${resource.yearLevel}  
**Type:** ${resource.type}  
**Quality Score:** ${resource.qualityScore.toFixed(1)}/15  
**Cultural Authenticity:** ${resource.culturalAuthenticity.toFixed(1)}/10  

## Description
${resource.description}

## Cultural Integration
This resource incorporates ${
      resource.culturalElements
    } cultural elements connecting learning to Te Ao Māori perspectives.

---
*Generated by Te Kete Ako Working Resource System*
    `;

    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${resource.title.replace(/[^a-z0-9]/gi, '_')}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  if (loading) {
    return (
      <div className="working-browser loading">
        <div className="loading-spinner">
          <BookOpen className="animate-spin" size={48} />
          <p>Loading working resources...</p>
          <div className="progress-bar">
            <div 
              className="progress-fill" 
              style={{ width: `${loadingProgress}%` }}
            ></div>
          </div>
          <p className="progress-text">{loadingProgress}% complete</p>
        </div>
      </div>
    );
  }

  return (
    <div className="working-browser">
      {/* Header */}
      <div className="browser-header">
        <div className="header-content">
          <h1>📚 Working Resource Browser</h1>
          <p className="subtitle">Actually working educational resources</p>
          <div className="stats">
            <span>{resources.length} resources loaded</span>
            <span>•</span>
            <span>{filteredResources.length} showing</span>
          </div>
        </div>
      </div>

      {/* Search and Filters */}
      <div className="search-filters">
        <div className="search-input-container">
          <Search size={20} />
          <input
            type="text"
            placeholder="Search resources..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="search-input"
          />
        </div>

        <div className="filter-controls">
          <select
            value={selectedSubject}
            onChange={(e) => setSelectedSubject(e.target.value)}
            className="filter-select"
          >
            <option value="all">All Subjects</option>
            {getSubjects().map((subject) => (
              <option key={subject} value={subject}>
                {subject}
              </option>
            ))}
          </select>

          <select
            value={selectedYearLevel}
            onChange={(e) => setSelectedYearLevel(e.target.value)}
            className="filter-select"
          >
            <option value="all">All Year Levels</option>
            {getYearLevels().map((yearLevel) => (
              <option key={yearLevel} value={yearLevel}>
                {yearLevel}
              </option>
            ))}
          </select>
        </div>
      </div>

      {/* Resources Grid */}
      <div className="resources-container">
        {filteredResources.length === 0 ? (
          <div className="no-resources">
            <BookOpen size={64} className="opacity-50" />
            <h3>No resources found</h3>
            <p>Try adjusting your search terms or filters</p>
          </div>
        ) : (
          <div className="resources-grid">
            {filteredResources.map((resource) => (
              <div key={resource.id} className="resource-card">
                <div className="card-header">
                  <div className="resource-type">
                    {getTypeIcon(resource.type)}
                    <span>{resource.type}</span>
                  </div>
                  <div className="quality-badge">
                    <Star size={16} />
                    {resource.qualityScore.toFixed(1)}
                  </div>
                </div>

                <div className="card-content">
                  <h3>{resource.title}</h3>
                  <p className="resource-description">{resource.description}</p>

                  <div className="resource-meta">
                    <span className="subject">{resource.subject}</span>
                    <span className="year-level">{resource.yearLevel}</span>
                  </div>

                  <div className="cultural-info">
                    <span className="cultural-elements">
                      🌿 {resource.culturalElements} cultural elements
                    </span>
                    <span className="cultural-auth">
                      Cultural Auth: {resource.culturalAuthenticity.toFixed(1)}/10
                    </span>
                  </div>
                </div>

                <div className="card-actions">
                  <button className="download-btn" onClick={() => downloadResource(resource)}>
                    <Download size={16} />
                    Download
                  </button>
                  <button
                    className="view-btn"
                    onClick={() => window.open(`/actual-content/${resource.id}`, '_blank')}
                  >
                    View Actual Content
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
};

export default WorkingResourceBrowser;
