/**
 * Actual Content Loader
 * Loads the real enriched content that was generated by our AI agents
 */

export interface ActualLesson {
  id: string;
  title: string;
  type: string;
  subject: string;
  yearLevel: string;
  culturalContext: string;
  depth: string;
  learningObjectives: string[];
  activities: Array<{
    title: string;
    description: string;
  }>;
  resources: string[];
  assessment: {
    type: string;
    tasks: string[];
  };
  duration?: string;
  nzcAlignment?: string[];
  createdAt: string;
  unitType?: string;
  groupSize?: string;
  unitStructure?: string[];
}

export interface ActualUnitPlan {
  id: string;
  title: string;
  type: string;
  subject: string;
  yearLevel: string;
  culturalContext: string;
  depth: string;
  learningObjectives: string[];
  activities: string[];
  resources: string[];
  assessment: {
    type: string;
    tasks: string[];
  };
  duration: string;
  nzcAlignment: string[];
  createdAt: string;
  unitType: string;
  groupSize: string;
  unitStructure: string[];
}

class ActualContentService {
  private lessonsCache: Map<string, ActualLesson> = new Map();
  private unitPlansCache: Map<string, ActualUnitPlan> = new Map();

  async loadActualLesson(lessonId: string): Promise<ActualLesson | null> {
    if (this.lessonsCache.has(lessonId)) {
      return this.lessonsCache.get(lessonId)!;
    }

    try {
      // Try to load from the actual lesson files
      const response = await fetch(`/content/lessons/${lessonId}.json`);
      if (response.ok) {
        const lesson: ActualLesson = await response.json();
        this.lessonsCache.set(lessonId, lesson);
        return lesson;
      }
    } catch (error) {
      console.warn(`Failed to load lesson ${lessonId}:`, error);
    }

    return null;
  }

  async loadActualUnitPlan(unitId: string): Promise<ActualUnitPlan | null> {
    if (this.unitPlansCache.has(unitId)) {
      return this.unitPlansCache.get(unitId)!;
    }

    try {
      const response = await fetch(`/content/unit-plans/${unitId}.json`);
      if (response.ok) {
        const unitPlan: ActualUnitPlan = await response.json();
        this.unitPlansCache.set(unitId, unitPlan);
        return unitPlan;
      }
    } catch (error) {
      console.warn(`Failed to load unit plan ${unitId}:`, error);
    }

    return null;
  }

  async getAllLessons(): Promise<ActualLesson[]> {
    // This would need to be implemented to scan the lessons directory
    // For now, return empty array
    return [];
  }

  async getAllUnitPlans(): Promise<ActualUnitPlan[]> {
    // This would need to be implemented to scan the unit-plans directory
    // For now, return empty array
    return [];
  }

  // Convert enhanced resource to actual content if we have it
  async getActualContentForResource(
    resourceId: string,
  ): Promise<ActualLesson | ActualUnitPlan | null> {
    // Try to find matching lesson or unit plan
    // This is a simplified mapping - in reality we'd need a proper mapping system
    const lessons = await this.getAllLessons();
    const unitPlans = await this.getAllUnitPlans();

    // Look for content that matches the resource
    const matchingLesson = lessons.find(
      (lesson) =>
        lesson.id.includes(resourceId) ||
        lesson.title.toLowerCase().includes(resourceId.toLowerCase()),
    );

    if (matchingLesson) return matchingLesson;

    const matchingUnitPlan = unitPlans.find(
      (unit) =>
        unit.id.includes(resourceId) || unit.title.toLowerCase().includes(resourceId.toLowerCase()),
    );

    if (matchingUnitPlan) return matchingUnitPlan;

    return null;
  }
}

const actualContentService = new ActualContentService();

export const loadActualLesson = (lessonId: string) =>
  actualContentService.loadActualLesson(lessonId);
export const loadActualUnitPlan = (unitId: string) =>
  actualContentService.loadActualUnitPlan(unitId);
export // const getAllActualLessons = () => actualContentService.getAllLessons();
export // const getAllActualUnitPlans = () => actualContentService.getAllUnitPlans();
export const getActualContentForResource = (resourceId: string) =>
  actualContentService.getActualContentForResource(resourceId);

export default actualContentService;
