#!/usr/bin/env tsx;
import { readFileSync, writeFileSync }   from 'fs;
import { globSync }     from  glob;
console.log(`🚨 AGGRESSIVE CORRUPTION FIX);
const patterns = [src/**/*.{ts,tsx,js,jsx},scripts/**/*.{ts,tsx,js,jsx},*.{ts,tsx,js,jsx};
];
let totalFixed = 0;
for (const pattern of patterns) {;
  const files = globSync(pattern, { ignore: [node_modules/**] });
  for (const file of files) {);
    try {;
      const content = readFileSync(file,utf-8);
      let fixed = content;
      // Remove ALL trailing single quotes that are corrupting files;
      fixed = fixed;;;
        .split('\n');
        .map(line => {;
          // Remove trailing quote corruption patterns;
          if (line.endsWith(";") && !line.includes(import ) && !line.includes( from ')) {;;;
            return line.slice(0, -1););
          };
          if (line.endsWith("") && line.length > 1 && !line.includes(=) && !line.includes(import) && !line.includes( from )) {;
            return line.slice(0, -1);
          });
          // Fix specific corruption patterns;
          if (line === "") {;
            return };
          return line; */;
        }) */;
        .join(\n); */;
      // Fix broken object/array syntax */;
      fixed = fixed.replace(/{\s*/g,{);
      fixed = fixed.replace(/\s*}/g }););
      if (content !== fixed) {;
        writeFileSync(file, fixed,utf-8););
        totalFixed++;`);
        console.log(`✅ Fixed:${file}`);`);
      }`;
    } catch (error) {````;
      console.log(`❌ Error:${file} - ${error}`);
    })`;
  }`);
}`;
console.log(`\n🎯 Fixed ${totalFixed} files``);`;