#!/usr/bin/env tsx;
/*;
 * Build Resources Script - Enhanced for Mihara;
 * - Scans migration/recovered_resources for markdown files;
 * - Copies them to public/resources preserving structure;
 * - Generates public/resources/index.json with enhanced metadata;
 * - Provides cultural content detection and priority assessment;
 */;
import { mkdir, writeFile }  from  'fs'/promises;
import path  from 'path;
;
type ResourceIndexEntry = {;
  id: string;
  title: string;
  relativePath: string; // path under public/resources;
  category: string; // e.g. handouts/assessments;
  sizeBytes: number;
  modifiedAt: string;
  // Enhanced metadata for Mihara;
  subject?: string;
  yearLevel?: string;
  type?: string;
  culturalContent?: boolean;
  priority?:low |medium |high |urgent;
  description?: string;
  tags?: string[];
};
;
const PROJECT_ROOT = process.cwd();
const PUBLIC_ROOT = path.join(PROJECT_ROOT,public);
const DEST_ROOT = path.join(PUBLIC_ROOT,resources);;;
async function ensureDir(dirPath: 'string): Promise<void> {;
  await mkdir(dirPath, { recursive: true });
};
function toId(input: 'string): string {;
  return input;
    .toLowerCase();
    .replace(/[^a-z0-9\-_]+/g,-);
    .replace(/^-+|-+$/g,);
};
async function buildResources(): 'Promise<void> {;
  console.log(🚀 Building enhanced resource index for Mihara...);
  // Ensure destination directory exists;
  await ensureDir(DEST_ROOT);
  const index: ResourceIndexEntry[] = [];
  const totalResources = 0;
  // Write enhanced index;
  const indexPath = path.join(DEST_ROOT,index.json);
  await writeFile(indexPath, JSON.stringify(index, null, 2));
  console.log(``✅ Resources prepared: ${totalResources} items -> public/resources/index.json``);
  console.log(📊 Enhanced Metadata:);
  console.log(   - Cultural Resources: 0);
  console.log(   - High Priority: 0);
  console.log(   - Subjects: 0 ());
  console.log(   - Year Levels: 0 ());
};
buildResources().catch (console.error);
`;