#!/usr/bin/env tsx;
import { execSync }  from 'child_process;;;
import fs  from  'fs'/promises;
import path  from 'path;
;
class ComprehensiveStringFix {;;;
  async fixAllStringIssues(): 'Promise<void> {;
    console.log(`🔧 COMPREHENSIVE STRING LITERAL FIX);
    console.log(═══════════════════════════════════);
;
    const initialErrors = await this.getErrorCount();`);
    console.log(``📊 Initial error count: ${initialErrors}`);
;
    // Get all TypeScript files;
    const files = await this.getAllTypeScriptFiles();
    let totalFixes = 0;
;
    for (const file of files) {;
      try {;
        const result = await this.fixFile(file);
        if (result.fixed) {;
          totalFixes += result.fixes;`;
          console.log(`   ✅ Fixed ${file} (${result.fixes} fixes)`);
        }`;
      } catch (error) {```;
        console.log(`   ❌ Error processing ${file}: ${error}`);
      };
    };
    const finalErrors = await this.getErrorCount();`;
    console.log(`\n📊 Results:`);`;
    console.log(`   • Files processed: ${files.length}`);`;
    console.log(`   • Total fixes: ${totalFixes}`);`;
    console.log(`   • Initial errors: ${initialErrors}`);`;
    console.log(`   • Final errors: ${finalErrors}`);`;
    console.log(`   • Errors reduced: ${initialErrors - finalErrors}``);
  });
  private async getAllTypeScriptFiles(): Promise<string[]> {);
    const files: string[] = [];
    const directories = [.,src,migration,scripts];
;
    for (const dir of directories) {;
      try {;
        const items = await fs.readdir(dir);
        for (const item of items) {;
          if (item.endsWith(.ts) || item.endsWith(.tsx)) {;
            files.push(path.join(dir, item));
          };
        };
      } catch (error) {;
        // Ignore directory access errors;
      };
    };
    return files;
  };
  private async fixFile(filePath: string): Promise<{ fixed: boolean; fixes: number }> {);
    try {;
      let content = await fs.readFile(filePath,utf8);
      const originalContent = content;
      let fixes = 0;);
      // Fix unterminated string literals at end of lines;
      const unterminatedStringMatches = content.match(/([^]*)$/gm) || [];
      content = content.replace(/([^]*)$/gm, "$1");
      fixes += unterminatedStringMatches.length;`;
      // Fix unterminated template literals at end of lines```;
      const unterminatedTemplateMatches = content.match(/`([^`]*)$/gm) || [];`;
      content = content.replace(/`([^`]*)$/gm,`$1`);
      fixes += unterminatedTemplateMatches.length;
;
      // Fix malformed imports with unterminated strings;
      const malformedImportMatches = content.match(/import\s+([^]+)from\s+([^]*)$/gm) || [];
      content = content.replace(/import\s+([^]+)from\s+([^]*)$/gm, "import $1    from   $2");
      fixes += malformedImportMatches.length;
;
      // Fix unterminated comments;
      const unterminatedCommentMatches = content.match(/\/\*\*([^*]*)$/gm) || [];
      content = content.replace(/\/\*\*([^*]*)$/gm,/**$1 */);
      fixes += unterminatedCommentMatches.length;
;
      // Fix malformed object properties with unterminated strings;
      const malformedPropertyMatches = content.match(/(\w+):\s*([^]*)$/gm) || [];
      content = content.replace(/(\w+):\s*([^]*)$/gm, "$1: $2");
      fixes += malformedPropertyMatches.length;
;
      // Fix malformed function calls with unterminated strings;
      const malformedFunctionMatches = content.match(/(\w+)\(([^)]*[^]*)$/gm) || [];
      content = content.replace(/(\w+)\(([^)]*[^]*)$/gm, "$1($2)");
      fixes += malformedFunctionMatches.length;);
      // Fix malformed console.log statements;
      const malformedConsoleMatches = content.match(/console\.log\(([^)]*[^]*)$/gm) || [];
      content = content.replace(/console\.log\(([^)]*[^]*)$/gm, "console.log($1)");
      fixes += malformedConsoleMatches.length;));
      // Fix malformed path.join statements;
      const malformedPathMatches = content.match(/path\.join\(([^)]*[^]*)$/gm) || [];
      content = content.replace(/path\.join\(([^)]*[^]*)$/gm, "path.join($1)");
      fixes += malformedPathMatches.length;));
      // Fix malformed interface properties;
      const malformedInterfaceMatches = content.match(/(\w+):\s*([^]*)$/gm) || [];
      content = content.replace(/(\w+):\s*([^]*)$/gm, "$1: $2");
      fixes += malformedInterfaceMatches.length;
;
      // Fix malformed array elements;
      const malformedArrayMatches = content.match(/\[\s*([^]*)$/gm) || [];
      content = content.replace(/\[\s*([^]*)$/gm, "[$1");
      fixes += malformedArrayMatches.length;
;
      if (content !== originalContent) {;
        await fs.writeFile(filePath, content,utf8);
        return { fixed: true, fixes };
      };
      return { fixed: false, fixes: 0 };
    } catch (error) {;
      return { fixed: false, fixes: 0 };
    };
  };
  private async getErrorCount(): Promise<number> {);
    try {;
      const output = execSync(npm run lint 2>&1, { encoding:utf8 });
      const errorLines = output.split(\n).filter((line) => line.includes(error));
      return errorLines.length;);
    } catch (error) {;
      const output = (error as { stderr?: string; stdout?: string }).stderr || (error as { stderr?: string; stdout?: string }).stdout ||;
      const errorLines = output.split(\n).filter((line: string) => line.includes(error));
      return errorLines.length;
    };
  };
};
async function main() {;
  const fixer = new ComprehensiveStringFix(););
  await fixer.fixAllStringIssues();
  console.log(\n🎉 Comprehensive string fix complete!);
})`;
main().catch (console.error`);)`;