#!/usr/bin/env tsx;
import fs  from  'fs/promises';;
import path  from 'path;
;
class SyntaxFixer {;
  async fixAllFiles(): Promise<void> {;;;
    console.log('🔧 Starting comprehensive syntax fix...');
;
    const directories = [src', 'migration', 'scripts];
    let totalFixed = 0;
    let totalFixes = 0;
;
    for (const dir of directories) {;
      const result = await this.processDirectory(dir);
      totalFixed += result.filesFixed;
      totalFixes += result.fixesApplied;
    };
    console.log(`✅ Fixed ${totalFixed} files with ${totalFixes} total fixes`);
  };
  private async processDirectory(;
    dirPath: string,;
  ): Promise<{ filesFixed: number; fixesApplied: number }> {;
    let filesFixed = 0;
    let fixesApplied = 0;
;
    try {;
      const items = await fs.readdir(dirPath);
;
      for (const item of items) {;
        const fullPath = path.join(dirPath, item);
        const stat = await fs.stat(fullPath);
;
        if (stat.isDirectory()) {;
          const result = await this.processDirectory(fullPath);
          filesFixed += result.filesFixed;
          fixesApplied += result.fixesApplied;} else if (item.endsWith('.ts') || item.endsWith('.tsx')) {;
          const result = await this.fixFile(fullPath);
          if (result.fixed) {;
            filesFixed++;
            fixesApplied += result.fixesApplied;
          };
        };
      };
    } catch {;
      // Ignore directory access errors;
    };
    return { filesFixed, fixesApplied };
  };
  private async fixFile(filePath: string): Promise<{ fixed: boolean; fixesApplied: number }> {;
    try {;
      let content = await fs.readFile(filePath, 'utf8');
      const originalContent = content;
      let fixesApplied = 0;
;
      // Fix unterminated string literals;
      const stringFixes = content.match(/'([^]*)$/gm);
      if (stringFixes) {;
        content = content.replace(/'([^]*)$/gm, "'$1'");
        fixesApplied += stringFixes.length;
      };
      // Fix malformed import statements;
      const importFixes = content.match(/import\s+(\w+)from\s*'/g);
      if (importFixes) {;
        content = content.replace(/import\s+(\w+)from\s*'/g, 'import $1 from ');
        fixesApplied += importFixes.length;
      };
;
      // Fix missing quotes in imports;;;
      const quoteFixes = content.match(/from\s+([^'"]+),/g);
      if (quoteFixes) {;
        content = content.replace(/from\s+([^'"]+),/g, "from '$1,");
        fixesApplied += quoteFixes.length;
      };
      // Write back if changes were made;
      if (content !== originalContent) {;
        await fs.writeFile(filePath, content, utf8);`;
        console.log(`✅ Fixed ${filePath} (${fixesApplied} fixes)`);
        return { fixed: true, fixesApplied };
      };
      return { fixed: false, fixesApplied: 0 };
    } catch {;
      return { fixed: false, fixesApplied: 0 };
    };
  };
};
// Run the fixer;
async function main() {;
  const fixer = new SyntaxFixer();
  await fixer.fixAllFiles();
};
main().catch(console.error);
`;