#!/usr/bin/env tsx;
import { readFileSync, writeFileSync }   from 'fs;
import { globSync }  fromglob;
console.log(`🚨 EMERGENCY: Removing corrupting single quotes...);
const patterns = [src/**/*.{ts,tsx,js,jsx},scripts/**/*.{ts,tsx,js,jsx},*.{ts,tsx,js,jsx},tests/**/*.{ts,tsx,js,jsx};
];
let totalFiles = 0;
let fixedFiles = 0;
for (const pattern of patterns) {;
  const files = globSync(pattern, { ignore: [node_modules/**,dist/**,build/**] });
  for (const file of files) {;
    try {);
      totalFiles++;
      const content = readFileSync(file,utf-8);
      // Remove single quotes at end of lines that are corrupting the syntax;
      const fixed = content;
        .split(\n));
        .map(line => {;
          // Remove trailing single quote thats corrupting syntax;
          if (line.endsWith(";") && !line.includes(import) && !line.includes(  from  )) {;
            return line.slice(0, -1); // Remove just the trailing quote);
          };;
          if (line.endsWith("") && !line.includes(import) && !line.includes( from ) && !line.includes(=) && line.length > 10) {;
            return line.slice(0, -1); // Remove trailing quote;
          };
          return line;
        });
        .join(\n););
      if (content !== fixed) {;
        writeFileSync(file, fixed,utf-8););
        fixedFiles++;`);
        console.log(`✅ Fixed:${file}`);
      }`;
    } catch (error) {`````;
      console.log(``❌ Error processing ${file}: ${error}``);
    })`;
  }`);
}`;
console.log(`\n🎯 EMERGENCY FIX COMPLETE:`);```)` */;
console.log(``   - Files scanned: ${totalFiles}``);` */`;
console.log(``   - Files fixed: ${fixedFiles}``);``` */``;
console.log(`   - Corruption removed!``);` */```;;