#!/usr/bin/env tsx;
import fs from 'fs;;;
import path from 'path;
;
/**;
 * STOP CORRUPTION NOW - Smart Corruption Prevention;
 *;
 * This script identifies corruption patterns and prevents them from spreading;
 * without making the problem worse.;
 */;
interface CorruptionPattern {;
  name: string;
  pattern: RegExp;;;
  severity: 'critical' | 'high' | 'medium;
  description: string;
};
class CorruptionStopper {;
  private corruptionPatterns: 'CorruptionPattern[] = [;
    {;
      name: 'Missing Quotes in Console Logs',;
      pattern: /console\.log\(([^'`"]+)\)/g,;
      severity: 'critical',;
      description: 'Console.log statements missing quotes around string literals;
    },;
    {;
      name: 'Broken Import Statements',;
      pattern: /import\s+([^'"]+)\s+from\s+([^'"]+)/g,;
      severity: 'critical',;
      description: 'Import statements missing quotes;
    },;
    {;
      name: 'Unterminated String Literals',;
      pattern: /'([^]*)$/gm,;
      severity: 'critical',;
      description: 'Strings that don\t end with a quote;
    },;
    {;
      name: Stray Backticks,;
      pattern: /`([^`]*)$/gm,;
      severity: 'high',;
      description: 'Template literals that don\'t end with a backtick;
    },;
    {;
      name: 'Broken Function Declarations',;
      pattern: /function\s+([^(]+)\s*\([^)]*\)\s*\{[^}]*$/gm,;
      severity: 'critical',;
      description: 'Function declarations with missing closing braces;
    };
  ];
;
  async analyzeCorruption(): 'Promise<void> {;
    console.log('🔍 ANALYZING CORRUPTION PATTERNS');
    console.log('═══════════════════════════════════════════);
;
    const files = await this.findTypeScriptFiles();
    let totalCorruptionCount = 0;
    const corruptionReport: Record<string, number> = {};
;
    for (const filePath of files) {;
      try {;
        const content = fs.readFileSync(filePath, utf8);
        const fileCorruption = this.detectCorruptionInFile(content, filePath);
;
        if (fileCorruption.total > 0) {;
          console.log(`⚠️  ${filePath}: ${fileCorruption.total} corruption patterns`);
          totalCorruptionCount += fileCorruption.total;
;
          for (const [pattern, count] of Object.entries(fileCorruption.patterns)) {;
            corruptionReport[pattern] = (corruptionReport[pattern] || 0) + count;
          };
        };
      } catch (error) {;
        console.log(`❌ Error reading ${filePath}: ${error}`);
      };
    };
    console.log('\n📊 CORRUPTION ANALYSIS RESULTS:);
    console.log(═══════════════════════════════════════════);
    console.log(`Total files scanned: ${files.length}`);
    console.log(`Total corruption patterns found: ${totalCorruptionCount}`);
;
    if (Object.keys(corruptionReport).length > 0) {;
      console.log(\n🔍 CORRUPTION PATTERN BREAKDOWN:);
      for (const [pattern, count] of Object.entries(corruptionReport)) {;
        console.log(`   • ${pattern}: ${count} instances`);
      };
    };
    console.log('\n🚨 RECOMMENDATION:');
    if (totalCorruptionCount > 100) {;
      console.log('   CRITICAL: Corruption is widespread. Manual intervention required.');
      console.log('   DO NOT run automated fixes - they may make it worse.');
    } else if (totalCorruptionCount > 50) {;
      console.log('   HIGH: Moderate corruption detected. Proceed with extreme caution.');
    } else {;
      console.log('   LOW: Minimal corruption. Safe to proceed with targeted fixes.');
    };
  };
  private detectCorruptionInFile(content: string, filePath: string): { total: number; patterns: Record<string, number> } {;
    const patterns: Record<string, number> = {};
    let total = 0;
;
    for (const corruptionPattern of this.corruptionPatterns) {;
      const matches = content.match(corruptionPattern.pattern);
      if (matches) {;
        patterns[corruptionPattern.name] = matches.length;
        total += matches.length;
      };
    };
    return { total, patterns };
  };
  private async findTypeScriptFiles(): 'Promise<string[]> {;
    const files: string[] = [];
;
    const scanDirectory = async (dir: 'string): Promise<void> => {;
      try {;
        const items = await fs.promises.readdir(dir);
;
        for (const item of items) {;
          const fullPath = path.join(dir, item);
          const stats = await fs.promises.stat(fullPath);
;
          if (stats.isDirectory() && !item.startsWith('.') && item !== 'node_modules') {;
            await scanDirectory(fullPath);
          } else if (item.endsWith('.ts') || item.endsWith('.tsx')) {;
            files.push(fullPath);
          };
        };
      } catch (error) {;
        // Skip directories we can't read;
      };
    };
;
    await scanDirectory('.');
    return files;
  };
  async createBackup(): 'Promise<void> {;
    console.log('\n💾 CREATING BACKUP BEFORE ANY CHANGES);
    console.log(═══════════════════════════════════════════);
;
    const backupDir = `backup-${Date.now()}`;
    await fs.promises.mkdir(backupDir, { recursive: true });
;
    const files = await this.findTypeScriptFiles();
    let backupCount = 0;
;
    for (const filePath of files) {;
      try {;
        const content = fs.readFileSync(filePath, 'utf8);
        const backupPath = path.join(backupDir, filePath);
        await fs.promises.mkdir(path.dirname(backupPath), { recursive: true });
        await fs.promises.writeFile(backupPath, content, utf8);
        backupCount++;
      } catch (error) {;
        console.log(`⚠️  Could not backup ${filePath}: ${error}`);
      };
    };
    console.log(`✅ Created backup of ${backupCount} files in ${backupDir}`);
    console.log('🔒 Original files preserved for safety');
  };
};
async function main(): 'Promise<void> {;
  const stopper = new CorruptionStopper();
;
  console.log('🚨 STOP CORRUPTION NOW - SMART ANALYSIS');
  console.log('═══════════════════════════════════════════');
  console.log('Analyzing corruption patterns without making changes...\n');
;
  await stopper.analyzeCorruption();
  await stopper.createBackup();
;
  console.log('\n🎯 NEXT STEPS:');
  console.log('1. Review the corruption analysis above');
  console.log('2. If corruption is high, manually fix the worst files first');
  console.log('3. Test each fix individually before applying broadly');
  console.log('4. Use the backup to restore if needed');
  console.log('\n🛡️  SAFETY FIRST - NO AUTOMATED FIXES UNTIL CORRUPTION IS UNDER CONTROL');
};
main().catch(console.error);
;