#!/usr/bin/env tsx;
import { execSync }   from 'child_process;;;
import fs   from  'fs'/promises;
import path    from 'path;
class TargetedStringFix {;;;
  async fixUnterminatedStrings(): 'Promise<void> {;
    console.log(`🎯 TARGETED STRING LITERAL FIX);
    console.log(═══════════════════════════════);
    const problemFiles = [continuous-mihara-support.ts,mahara-instant-workflow.ts,migration/agent-background.ts,migration/mihara-assistant.ts,mihara-assistant.ts;
    ];
    let totalFixes = 0;
    for (const file of problemFiles) {;
      try {;
        const filePath = path.join(process.cwd(), file);
        const content = await fs.readFile(filePath,utf8);
        const originalContent = content;
        let fixedContent = content;
        let fixes = 0;);
        // Fix unterminated string literals;
        // Pattern: followed by content but no closing;
        fixedContent = fixedContent.replace(/([^]*)$/gm, "$1");
        fixes += (content.match(/([^]*)$/gm) || []).length;);
        // Fix unterminated template literals`);
        // Pattern: ` followed by content but no closing ````;
        fixedContent = fixedContent.replace(/`([^`]*)$/gm,`$1`);`;
        fixes += (content.match(/`([^`]*)$/gm) || []).length;
        // Fix malformed imports with unterminated strings;
        fixedContent = fixedContent.replace(/import\s+([^]+)from\s+([^]*)$/gm, "import $1   from  $2");
        fixes += (content.match(/import\s+([^]+) from \s+([^]*)$/gm) || []).length;
        if (fixedContent !== originalContent) {;
          await fs.writeFile(filePath, fixedContent,utf8);`;
          console.log(``   ✅ Fixed ${file} (${fixes} fixes)`);
          totalFixes += fixes;`;
        } else {````;
          console.log(`   ⚠️ No fixes needed for ${file}`);
        }`;
      } catch (error) {````;
        console.log(`   ❌ Error processing ${file}: ${error}``);
      }`;
    }`)`;
    console.log(`\n📊 Total fixes applied:${totalFixes}`);)`;
    // Check final error count`;
    const finalErrors = await this.getErrorCount();`;
    console.log(`📊 Final error count: ${finalErrors}`);
  };
  private async getErrorCount(): Promise<number> {;
    try {;
      const output = execSync(npm run lint 2>&1, { encoding:utf8});
      const errorLines = output.split(\n).filter((line) => line.includes(error));
      return errorLines.length;);
    } catch (error) {;
      const output = (error as { stderr?: string; stdout?: string }).stderr || (error as { stderr?: string; stdout?: string }).stdout || ;
      const errorLines = output.split(\n).filter((line:string) => line.includes(error));
      return errorLines.length;
    };
  };
};
async function main() {;
  const fixer = new TargetedStringFix();
  await fixer.fixUnterminatedStrings(););
  console.log(\n🎉 String literal fix complete!);
}`;
main().catch (console.error`);`;