import React from 'react';
import './ArtOfHakaHandout.css';

/**
 * Handout: The Art of Haka
 * 
 * Educational handout component for Te Kete Ako platform
 * Generated by SuperClaude Content Extraction Army
 * Cultural Safety Protocol: ACTIVE
 */

interface ArtOfHakaHandoutProps {
  className?: string;
  title?: string;
}

export const ArtOfHakaHandout: React.FC<ArtOfHakaHandoutProps> = ({
  className = "",
  title = "Handout: The Art of Haka",
  ...props
}) => {
  return (
    <div 
      className={`handout-container ${componentName.toLowerCase()}-handout ${className}`}
      {...props}
    >
      <div className="handout-header">
        <h1 className="handout-title">{title}</h1>
      </div>
      
      <div className="handout-content">
        <div className="container"> <h1 className="wiley-hero-title">Handout: The Art of Haka</h1> <p>This handout supports the video "Kapa Haka | NPR".</p> <p><a href="https://www.youtube.com/watch?v=QIwLu22b6QU" target="_blank" rel="noopener">Watch the video</a></p> <h2 className="wiley-section-title">Key Discussion Points</h2> <ul> <li>What are the different elements of a Kapa Haka performance?</li> <li>What is the cultural significance of the Haka?</li> <li>How does the Haka connect to Māori identity and storytelling?</li> </ul> </div> <script src="js/supabase-client.js"></script> <script src="js/auth-enhanced.js"></script>
      </div>
    </div>
  );
};

export default ArtOfHakaHandout;
