import React from 'react';
import './ClimateEmergencyAotearoaHandout.css';

/**
 * Handout: Climate Change in Aotearoa
 * 
 * Educational handout component for Te Kete Ako platform
 * Generated by SuperClaude Content Extraction Army
 * Cultural Safety Protocol: ACTIVE
 */

interface ClimateEmergencyAotearoaHandoutProps {
  className?: string;
  title?: string;
}

export const ClimateEmergencyAotearoaHandout: React.FC<ClimateEmergencyAotearoaHandoutProps> = ({
  className = "",
  title = "Handout: Climate Change in Aotearoa",
  ...props
}) => {
  return (
    <div 
      className={`handout-container ${componentName.toLowerCase()}-handout ${className}`}
      {...props}
    >
      <div className="handout-header">
        <h1 className="handout-title">{title}</h1>
      </div>
      
      <div className="handout-content">
        <div className="container"> <h1 className="wiley-hero-title">Handout: Climate Change in Aotearoa</h1> <p>This handout supports the video "Declaring a Climate Emergency".</p> <p><a href="https://www.youtube.com/watch?v=A-sA182-yoA" target="_blank" rel="noopener">Watch the video</a></p> <h2 className="wiley-section-title">Key Discussion Points</h2> <ul> <li>What does it mean for a government to declare a "climate emergency"?</li> <li>What are the concerns of the young people featured in the video?</li> <li>What actions do they believe are necessary to address climate change?</li> </ul> </div> <script src="js/supabase-client.js"></script> <script src="js/auth-enhanced.js"></script>
      </div>
    </div>
  );
};

export default ClimateEmergencyAotearoaHandout;
