import React from 'react';
import './ClimateChangeAotearoaHandout.css';

/**
 * Handout: Climate Change in Aotearoa
 * 
 * Educational handout component for Te Kete Ako platform
 * Generated by SuperClaude Content Extraction Army
 * Cultural Safety Protocol: ACTIVE
 */

interface ClimateChangeAotearoaHandoutProps {
  className?: string;
  title?: string;
}

export const ClimateChangeAotearoaHandout: React.FC<ClimateChangeAotearoaHandoutProps> = ({
  className = "",
  title = "Handout: Climate Change in Aotearoa",
  ...props
}) => {
  return (
    <div 
      className={`handout-container ${componentName.toLowerCase()}-handout ${className}`}
      {...props}
    >
      <div className="handout-header">
        <h1 className="handout-title">{title}</h1>
      </div>
      
      <div className="handout-content">
        <div className="container"> <h1 className="wiley-hero-title">Handout: Climate Change in Aotearoa</h1> <p>This handout supports the video "Climate Change in Aotearoa".</p> <p><a href="https://www.youtube.com/watch?v=HtTMSCVFbFg" target="_blank" rel="noopener">Watch the video</a></p> <h2 className="wiley-section-title">Key Discussion Points</h2> <ul> <li>What are the main impacts of climate change discussed in the video?</li> <li>How are young people in New Zealand responding to the climate crisis?</li> <li>What solutions or actions are proposed in the video?</li> </ul> </div> <script src="js/supabase-client.js"></script> <script src="js/auth-enhanced.js"></script>
      </div>
    </div>
  );
};

export default ClimateChangeAotearoaHandout;
