import React from 'react';
import './EcosystemSurveyChecklist.css';

/**
 * Ecosystem Survey Checklist (Y7)
 * 
 * Educational handout component for Te Kete Ako platform
 * Generated by SuperClaude Content Extraction Army
 * Cultural Safety Protocol: ACTIVE
 */

interface EcosystemSurveyChecklistProps {
  className?: string;
  title?: string;
}

export const EcosystemSurveyChecklist: React.FC<EcosystemSurveyChecklistProps> = ({
  className = "",
  title = "Ecosystem Survey Checklist (Y7)",
  ...props
}) => {
  return (
    <div 
      className={`handout-container ${componentName.toLowerCase()}-handout ${className}`}
      {...props}
    >
      <div className="handout-header">
        <h1 className="handout-title">{title}</h1>
      </div>
      
      <div className="handout-content">
        <h1 className="wiley-hero-title">Ecosystem Survey Checklist</h1> <p>Use with the Kaitiakitanga Field Journal. Tally observations and note evidence.</p> <table> <thead> <tr> <th>Item</th> <th>Observed?</th> <th>Evidence/Notes</th> </tr> </thead> <tbody> <tr> <td>Water clarity (clear / cloudy / algal bloom)</td> <td>[ ]</td> <td></td> </tr> <tr> <td>Native plants present (list)</td> <td>[ ]</td> <td></td> </tr> <tr> <td>Introduced/invasive species (list)</td> <td>[ ]</td> <td></td> </tr> <tr> <td>Invertebrates (e.g., kōura, kākahi, mayfly)</td> <td>[ ]</td> <td></td> </tr> <tr> <td>Birdlife (species, behaviour)</td> <td>[ ]</td> <td></td> </tr> <tr> <td>Human impacts (litter, erosion, runoff, barriers)</td> <td>[ ]</td> <td></td> </tr> <tr> <td>Evidence of restoration (planting, fencing, traps)</td> <td>[ ]</td> <td></td> </tr> <tr> <td>Tikanga upheld (karakia, access permission, respect)</td> <td>[ ]</td> <td></td> </tr> </tbody> </table>
      </div>
    </div>
  );
};

export default EcosystemSurveyChecklist;
