import React from 'react';
import './KaitiakitangaFieldJournal.css';

/**
 * Kaitiakitanga Field Journal (Y7)
 * 
 * Educational handout component for Te Kete Ako platform
 * Generated by SuperClaude Content Extraction Army
 * Cultural Safety Protocol: ACTIVE
 */

interface KaitiakitangaFieldJournalProps {
  className?: string;
  title?: string;
}

export const KaitiakitangaFieldJournal: React.FC<KaitiakitangaFieldJournalProps> = ({
  className = "",
  title = "Kaitiakitanga Field Journal (Y7)",
  ...props
}) => {
  return (
    <div 
      className={`handout-container ${componentName.toLowerCase()}-handout ${className}`}
      {...props}
    >
      <div className="handout-header">
        <h1 className="handout-title">{title}</h1>
      </div>
      
      <div className="handout-content">
        <h1 className="heading" className="wiley-hero-title">Kaitiakitanga Field Journal</h1> <p className="small">Use this journal to record observations and decisions during your ecosystem study. Be respectful and follow local tikanga.</p> <section className="grid"> <div className="box"> <h3 className="heading">Site & Conditions</h3> <p>Date/Time: __________ Weather: __________ Tide/Flow: __________</p> <p>Location (English & Māori names): ____________________________________</p> </div> <div className="box"> <h3 className="heading">Roles & Whakawhanaungatanga</h3> <p>Our group roles: ___________________________________________</p> <p>Karakia / safety notes: ______________________________________</p> </div> </section> <section className="box" style="margin-top:1rem"> <h3 className="heading">Observations (biotic & abiotic)</h3> <p style="min-height:220px;border:1px dashed #e1e5e9;border-radius: var(--radius-md);padding:.5rem">Sketches, counts, tracks, plants, insects, water clarity, substrate, sounds, signs of stress...</p> </section> <section className="grid" style="margin-top:1rem"> <div className="box"> <h3 className="heading">Food Web Notes</h3> <p>Key species and interactions (arrows for energy flow):</p> <div style="min-height:160px;border:1px dashed #e1e5e9;border-radius: var(--radius-md)"></div> </div> <div className="box"> <h3 className="heading">Kaitiaki Reflections</h3> <p>What responsibilities do we have here? Who should we consult (iwi/hapū, community)?</p> <div style="min-height:160px;border:1px dashed #e1e5e9;border-radius: var(--radius-md)"></div> </div> </section> <section className="box" style="margin-top:1rem"> <h3 className="heading">Action Ideas</h3> <ul> <li>What evidence suggests a pressure or imbalance?</li> <li>What small actions could help (monitoring, restoration, behaviour change)?</li> <li>How will we uphold tikanga and community partnerships?</li> </ul> </section>
      </div>
    </div>
  );
};

export default KaitiakitangaFieldJournal;
