import React from 'react';
import './MaoriNavigationWayfindingHandout.css';

/**
 * Handout: Māori Navigation
 * 
 * Educational handout component for Te Kete Ako platform
 * Generated by SuperClaude Content Extraction Army
 * Cultural Safety Protocol: ACTIVE
 */

interface MaoriNavigationWayfindingHandoutProps {
  className?: string;
  title?: string;
}

export const MaoriNavigationWayfindingHandout: React.FC<MaoriNavigationWayfindingHandoutProps> = ({
  className = "",
  title = "Handout: Māori Navigation",
  ...props
}) => {
  return (
    <div 
      className={`handout-container ${componentName.toLowerCase()}-handout ${className}`}
      {...props}
    >
      <div className="handout-header">
        <h1 className="handout-title">{title}</h1>
      </div>
      
      <div className="handout-content">
        <div className="container"> <h1 className="wiley-hero-title">Handout: Māori Navigation</h1> <p>This handout supports the video "The Art of Wayfinding".</p> <p><a href="https://www.youtube.com/watch?v=p-Zk-LQJ4sI" target="_blank" rel="noopener">Watch the video</a></p> <h2 className="wiley-section-title">Key Discussion Points</h2> <ul> <li>What is "wayfinding" and how does it differ from modern navigation?</li> <li>What natural signs do wayfinders use to navigate the ocean?</li> <li>Why is the revival of waka hourua and wayfinding important for Māori culture?</li> </ul> </div> <script src="js/supabase-client.js"></script> <script src="js/auth-enhanced.js"></script>
      </div>
    </div>
  );
};

export default MaoriNavigationWayfindingHandout;
