import React from 'react';
import './MediaLiteracyComprehensionHandout.v2.css';

/**
 * Media Literacy: Navigating the Digital World
 * 
 * Educational handout component for Te Kete Ako platform
 * Generated by SuperClaude Content Extraction Army
 * Cultural Safety Protocol: ACTIVE
 */

interface MediaLiteracyComprehensionHandout.v2Props {
  className?: string;
  title?: string;
}

export const MediaLiteracyComprehensionHandout.v2: React.FC<MediaLiteracyComprehensionHandout.v2Props> = ({
  className = "",
  title = "Media Literacy: Navigating the Digital World",
  ...props
}) => {
  return (
    <div 
      className={`handout-container ${componentName.toLowerCase()}-handout ${className}`}
      {...props}
    >
      <div className="handout-header">
        <h1 className="handout-title">{title}</h1>
      </div>
      
      <div className="handout-content">
        <section className="handout-section"> <h2 className="wiley-section-title">The Information Maze</h2> <p>Today, anyone can be a publisher. This is exciting, but it also means we need to be careful. Misinformation (accidental falsehoods) and disinformation (deliberate lies) can spread like wildfire. This handout will give you the tools to spot them.</p> </section> <section className="handout-section"> <h2 className="wiley-section-title">Why Does Fake News Spread So Fast?</h2> <p>A study by MIT found that false news is <strong>70% more likely</strong> to be shared than the truth. Why? Because it's often designed to be shocking, emotional, and to confirm what we already believe (this is called confirmation bias).</p> </section> <div className="task-box"> <h3>Task 1: Spot the Difference</h3> <p>In your own words, what is the difference between misinformation and disinformation? Think about intent.</p> </div> <div className="task-box"> <h3>Task 2: Filter Bubbles</h3> <p>Social media uses algorithms to show you things it thinks you'll like. How could this create a "filter bubble" or "echo chamber"? What are the dangers of only hearing opinions you agree with?</p> </div> <section className="handout-section"> <h2 className="wiley-section-title">Your Critical Thinking Toolkit</h2> <p>Before you believe or share something, ask these questions:</p> <ul> <li><strong>Who created this?</strong> Are they a real person? An expert?</li> <li><strong>What is the source?</strong> Is it a reputable news organisation or a random blog?</li> <li><strong>Why was this made?</strong> To inform? To persuade? To make you angry?</li> <li><strong>How can I check this?</strong> Can you find the same information on other trusted websites?</li> </ul> </section> <div className="task-box"> <h3>Task 3: You're the Detective</h3> <p>You see a headline: "Scientists Announce That Gaming Makes You a Genius!" What are two steps you would take to check if this is true?</p> </div>
      </div>
    </div>
  );
};

export default MediaLiteracyComprehensionHandout.v2;
