import React from 'react';
import './NzHousingCrisisHandout.css';

/**
 * Handout: NZ Housing Crisis
 * 
 * Educational handout component for Te Kete Ako platform
 * Generated by SuperClaude Content Extraction Army
 * Cultural Safety Protocol: ACTIVE
 */

interface NzHousingCrisisHandoutProps {
  className?: string;
  title?: string;
}

export const NzHousingCrisisHandout: React.FC<NzHousingCrisisHandoutProps> = ({
  className = "",
  title = "Handout: NZ Housing Crisis",
  ...props
}) => {
  return (
    <div 
      className={`handout-container ${componentName.toLowerCase()}-handout ${className}`}
      {...props}
    >
      <div className="handout-header">
        <h1 className="handout-title">{title}</h1>
      </div>
      
      <div className="handout-content">
        <div className="container"> <h1 className="wiley-hero-title">Handout: NZ Housing Crisis</h1> <p>This handout supports the video "Inside New Zealand's housing crisis".</p> <p><a href="https://www.youtube.com/watch?v=r-F-4F_i8mE" target="_blank" rel="noopener">Watch the video</a></p> <h2 className="wiley-section-title">Key Discussion Points</h2> <ul> <li>What are the main factors contributing to the housing crisis in New Zealand?</li> <li>How does the housing crisis affect young people and families?</li> <li>What are some of the potential solutions discussed in the video?</li> </ul> </div> <script src="js/supabase-client.js"></script> <script src="js/auth-enhanced.js"></script>
      </div>
    </div>
  );
};

export default NzHousingCrisisHandout;
