import React from 'react';
import './TedPowerYetHandout.css';

/**
 * Handout: The Power of Yet
 * 
 * Educational handout component for Te Kete Ako platform
 * Generated by SuperClaude Content Extraction Army
 * Cultural Safety Protocol: ACTIVE
 */

interface TedPowerYetHandoutProps {
  className?: string;
  title?: string;
}

export const TedPowerYetHandout: React.FC<TedPowerYetHandoutProps> = ({
  className = "",
  title = "Handout: The Power of Yet",
  ...props
}) => {
  return (
    <div 
      className={`handout-container ${componentName.toLowerCase()}-handout ${className}`}
      {...props}
    >
      <div className="handout-header">
        <h1 className="handout-title">{title}</h1>
      </div>
      
      <div className="handout-content">
        <div className="container"> <h1 className="wiley-hero-title">Handout: The Power of Yet</h1> <p>This handout supports the TED talk "The Power of Yet" by Carol Dweck.</p> <p><a href="https://www.youtube.com/watch?v=J-swZaKN2Ic" target="_blank" rel="noopener">Watch the video</a></p> <h2 className="wiley-section-title">Key Discussion Points</h2> <ul> <li>What is the difference between a "fixed mindset" and a "growth mindset"?</li> <li>How can the phrase "not yet" change our approach to challenges?</li> <li>What are some ways you can apply the "power of yet" in your own learning?</li> </ul> </div> <script src="js/supabase-client.js"></script> <script src="js/auth-enhanced.js"></script>
      </div>
    </div>
  );
};

export default TedPowerYetHandout;
