import React from 'react';
import './TreatyOfWaitangiHandout.css';

/**
 * Handout: The Treaty of Waitangi
 * 
 * Educational handout component for Te Kete Ako platform
 * Generated by SuperClaude Content Extraction Army
 * Cultural Safety Protocol: ACTIVE
 */

interface TreatyOfWaitangiHandoutProps {
  className?: string;
  title?: string;
}

export const TreatyOfWaitangiHandout: React.FC<TreatyOfWaitangiHandoutProps> = ({
  className = "",
  title = "Handout: The Treaty of Waitangi",
  ...props
}) => {
  return (
    <div 
      className={`handout-container ${componentName.toLowerCase()}-handout ${className}`}
      {...props}
    >
      <div className="handout-header">
        <h1 className="handout-title">{title}</h1>
      </div>
      
      <div className="handout-content">
        <div className="container"> <h1 className="wiley-hero-title">Handout: The Treaty of Waitangi</h1> <p>This handout supports the video "The Treaty of Waitangi explained, simply".</p> <p><a href="https://www.youtube.com/watch?v=a-yXA-a-t1E" target="_blank" rel="noopener">Watch the video</a></p> <h2 className="wiley-section-title">Key Discussion Points</h2> <ul> <li>What are the three main articles of the Treaty of Waitangi?</li> <li>What are the key differences between the English and Māori versions of the Treaty?</li> <li>Why is the Treaty of Waitangi still important today?</li> </ul> </div> <script src="js/supabase-client.js"></script> <script src="js/auth-enhanced.js"></script>
      </div>
    </div>
  );
};

export default TreatyOfWaitangiHandout;
