import React  from 'react;;;
const Year9StarterPackAlphaBuild: 'React.FC = () => {;
  return (;
    <div className="year9-starter-pack">;
      <h1>Year 9 Starter Pack - Alpha Build</h1>;
      <div className="content-section">;
        <h2>Essential Skills Development</h2>;
        <p>;
          Welcome to Year 9! This starter pack provides foundational skills and;
          cultural understanding for success in secondary education.;
        </p>;
        <section className="skill-areas">;
          <div className="skill-category">;
            <h3>Academic Foundations</h3>;
            <ul>;
              <li>Critical thinking development</li>;
              <li>Research methodology</li>;
              <li>Digital literacy skills</li>;
              <li>Time management strategies</li>;
            </ul>;
          </div>;
          <div className="skill-category">;
            <h3>Cultural Competency</h3>;
            <ul>;
              <li>Te Ao Māori perspectives</li>;
              <li>Bicultural understanding</li>;
              <li>Community engagement</li>;
              <li>Cultural safety practices</li>;
            </ul>;
          </div>;
          <div className="skill-category">;
            <h3>Communication Skills</h3>;
            <ul>;
              <li>Written expression</li>;
              <li>Oral presentation</li>;
              <li>Collaborative discussion</li>;
              <li>Digital communication</li>;
            </ul>;
          </div>;
        </section>;
        <section className="activities">;
          <h3>Practice Activities</h3>;
          <div className="activity-grid">;
            <div className="activity-card">;
              <h4>Research Project</h4>;
              <p>Choose a local community issue and research its cultural and historical context.</p>;
            </div>;
            <div className="activity-card">;
              <h4>Presentation Skills</h4>;
              <p>Present your findings incorporating both academic and mātauranga Māori perspectives.</p>;
            </div>;
            <div className="activity-card">;
              <h4>Collaborative Learning</h4>;
              <p>Work with peers to develop solutions that honor diverse viewpoints.</p>;
            </div>;
          </div>;
        </section>;
      </div>;
    </div>;
  );};;
;
export default Year9StarterPackAlphaBuild;;